In [13]:
# Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [14]:
"""
Ans. Yes, there is a difference in the data type of the variables list_ and array_list. The variable list_ is a 
     Python list, and array_list is a NumPy array.
"""
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_), list_)
print("Data type of array_list:", type(array_list), array_list)


Data type of list_: <class 'list'> ['1', '2', '3', '4', '5']
Data type of array_list: <class 'numpy.ndarray'> ['1' '2' '3' '4' '5']


In [15]:
# Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

In [16]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of each element in the list
print("Data types in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in the NumPy array
print("\nData types in array_list:")
for element in array_list:
    print(type(element))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [17]:
# Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#arra_list? If so then print the data types of each and every element present in both the variables, list_
#and arra_list.

In [18]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of each element in the list
print("Data types in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in the NumPy array with dtype=int
print("\nData types in array_list:")
for element in array_list:
    print(type(element))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [19]:
# Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

In [20]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of num_array
shape_of_array = num_array.shape
print("(i) Shape of num_array:", shape_of_array)

# (ii) Find the size of num_array
size_of_array = num_array.size
print("(ii) Size of num_array:", size_of_array)

(i) Shape of num_array: (2, 3)
(ii) Size of num_array: 6


In [21]:
# Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#creation function.
#[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [22]:
import numpy as np

zeros_array = np.zeros((3, 3))

print("Array of zeros:")
print(zeros_array)


Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Create an identity matrix of shape (5,5) using numpy functions?

In [24]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

print("Identity Matrix:")
print(identity_matrix)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
